### ISSUE TITLE
Cannot initialize a domain in python console

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#392]
Trying to initialize a domain in the python console throws a spec error because Protean expects the domain file to be in a package/folder.

`publishing = Domain(__name__)`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/subhashb/wspace/proteanhq/protean/src/protean/domain/__init__.py", line 134, in __init__
    _PackageBoundObject.__init__(
  File "/Users/subhashb/wspace/proteanhq/protean/src/protean/domain/helpers.py", line 92, in __init__
    root_path = get_root_path(self.import_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/subhashb/wspace/proteanhq/protean/src/protean/domain/helpers.py", line 43, in get_root_path
    loader = importlib.util.find_spec(import_name)
```

**Comment by subhashb** [comment]
This issue has been fixed with enhancements to `Domain`, notably the change that the domain now needs the explicit path `__file__` to be passed during domain initialization.
